# .rubocop.yml
AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'Gemfile'
    - 'lib/tasks/*.rake'
    - 'bin/*'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'spec/spec_helper.rb'
    - 'db/migrate/*'
Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'spec/factories/**/*'
Style/Documentation:
  Enabled: false
