# Omakase Ruby styling for Rails
require:
  - rubocop-erb
inherit_gem: { rubocop-rails-omakase: rubocop.yml }
# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true
